[package]
name = "kms-edwards25519"
description = "HD key derivation library for Ed25519 signature scheme"
version = "0.1.0"
edition = "2021"
authors = [
    "Matan Hamilis <matan.hamilis@gmail.com>"
]
exclude = [".gitignore", ".github/"]

[dependencies]
curve25519-dalek = "3"
blake2 = "0.10"

[dev-dependencies]
rand_xoshiro = "0.6.0"

[build]
rustdocflags = [ "--html-in-header", "docs_header.html" ]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./docs_header.html", "--cfg", "docsrs" ]